apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-secret
  name: pod-with-secret
spec:
  containers:
  - image: fsadykov/docker-testing
    name: secret-using
    command: ["python"]
    args: ["/app/app.py", "--name", "appone"]
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username

      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
